Group_Project/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Group_Project.EF;
using Group_Project.Models;

namespace Group_Project.Controllers
{
    public class LoginController : Controller
    {

        EcoImpactEntities db = new EcoImpactEntities();
        static UserMaster user;     //use in forgot password
        static int otp;             //use in forgot password

        // GET: View
        public ActionResult Index()
        {
            return PartialView();// View();
        }

        //login to account - set session variable
        public ActionResult Login(string username, string password)
        {
            //hash the users password
            MD5 md5 = new MD5CryptoServiceProvider();
            Byte[] originalBytes = ASCIIEncoding.Default.GetBytes(password);
            Byte[] encodedBytes = md5.ComputeHash(originalBytes);

            string pw = Convert.ToBase64String(encodedBytes);
            if(pw.Length > 64)
                pw = pw.Substring(0, 63);

            UserMaster u = db.UserMasters.FirstOrDefault(us => us.Username.Replace(" ", "").ToLower() == username.ToLower() || us.Email.Replace(" ", "").ToLower() == username.ToLower());

            if(u == null)
            {
                //invalid username
                Session["UserID"] = null;
                ViewBag.invalid = "username";
            }
            else
            {
                if(u.Password.Replace(" ", "") != pw.Replace(" ", ""))
                {
                    //invalid password
                    Session["UserID"] = null;
                    ViewBag.invalid = "password";
                }
                else
                {

                    Session["UserID"] = u.UserID;

                    //admin user
                    if (u.TypeID == 1)
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    //normal user
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }

            return View("Index");
        }

        //sends email to user with otp
        public ActionResult ResetPassword(int question, string answer, string email)
        {
            user = db.UserMasters.Where(u => u.Email.Replace(" ", "") == email).FirstOrDefault();

            if(user == null)
            {
                ViewBag.invalid = "invalid email";

                List<SecurityQuestion> q = db.SecurityQuestions.ToList();

                return View("ForgotPassword", q);
            }
            else
            {
                if(user.SecurityID != question)
                {
                    ViewBag.invalid = "invalid question";

                    List<SecurityQuestion> q = db.SecurityQuestions.ToList();

                    return View("ForgotPassword", q);
                }
                else
                {
                    if (user.SecurityAnswer.Replace(" ", "").ToLower() != answer.ToLower())
                    {
                        ViewBag.invalid = "invalid answer";

                        List<SecurityQuestion> q = db.SecurityQuestions.ToList();

                        return View("ForgotPassword", q);
                    }
                }
            } 

            try
            {
                Random rnd = new Random();
                otp = rnd.Next(1000000, 9999999);

                GMailer.GmailUsername = "ecoImpactWeb@gmail.com";
                GMailer.GmailPassword = "ecoImpact2020";

                GMailer mailer = new GMailer();
                mailer.ToEmail = user.Email.Replace(" ", "");
                mailer.Subject = "EcoImpact Reset Password OTP";
                mailer.Body = "<p>Please go to the EcoImpact website and enter the following One Time Pin:<p>  <a>"+ otp +"</a>";
                mailer.IsHtml = true;
                mailer.Send();

            }
            catch (Exception ex)
            {

                throw;
            }
           

            return View("ResetPassword");
        }

        //updates the password
        public ActionResult UpdatePassword(int userOTP, string userPassword)
        {
            if(userOTP != otp)
            {
                ViewBag.invalid = "invalid";
                return View("ResetPassword");
            }

            //hash the users password
            MD5 md5 = new MD5CryptoServiceProvider();
            Byte[] originalBytes = ASCIIEncoding.Default.GetBytes(userPassword);
            Byte[] encodedBytes = md5.ComputeHash(originalBytes);

            string pw = Convert.ToBase64String(encodedBytes);
            if (pw.Length > 64)
                pw = pw.Substring(0, 64);

            ViewBag.invalid = "valid";

            var u = db.UserMasters.FirstOrDefault(us => us.Email == user.Email);

            u.Password = pw;

            db.SaveChanges();

            return View("ResetPassword");
        }
        
        //return forgot password view
        public ActionResult ForgotPassword()
        {
            List<SecurityQuestion> question = db.SecurityQuestions.ToList();
            return View("ForgotPassword", question);
        }
    }
}

Group_Project/Views/Login/ForgotPassword.cshtml
@model List<Group_Project.EF.SecurityQuestion>
@{
    ViewBag.Title = "ForgotPassword";
    Layout = null;
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="~/Style/Style.css" />
<link rel="stylesheet" href="~/Style/DouglasStyles.css" />
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">



@using (Html.BeginForm("ResetPassword", "Login", FormMethod.Post))
{
    <div class="containerDiv container col-lg-6 col-md-7 col-sm-8" style="text-align: left;">
        <div class="clearfix">
            <img src="~/Images/logo.png" width="130" style="float: left;margin-right: 40px;">
            <h3 style="font-weight: bold;margin-top: 50px;">Forgot your Password?</h3>
            <h5>Answer your chosen security question correctly to proceed and reset your password</h5>
        </div>
        <br>
        <form style="border: none;">
            <div class="form-group ml-5">
                <h5><b>QUESTIONS</b></h5>
                <div class="contentBox2">
                    <div style="padding: 0;border: 0;margin:0;">
                        <select name="question" class="custom-select" size="5" class="form-control" id="selectQuestion" style="overflow: hidden; border: none;">
                            @foreach (var question in Model)
                            {
                                <option value="@question.SecurityID">@question.Question</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <br>
            <div class="form-group ml-5" style="width: 80%;">
                <label for="questionAnswer">Answer</label><br />
                <input type="text" class="form-control" name="answer" id="questionAnswer" placeholder="Please type the above selected question answer here...">
            </div>
            <div class="form-group ml-5" style="width: 80%;">
                <label for="recoverEmail">Email Address</label><br />
                <input type="email" class="form-control" name="email" id="recoverEmail" placeholder="Enter email">
            </div>
            <input type="submit" id="submitBtn" class="btn btn-group" style="width: 15%;margin-left: 84%;color: black;" />
        </form>
        <br>
    </div>
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="~/Scripts/ForgotPasswordScript.js"></script>

@if (ViewBag.invalid == "invalid email")
{
    <script>
        $.confirm({
            columnClass: 'col-6 text-left',
            title: 'Invalid Email',
            content: 'You Entered An Invalid Email',
            type: 'red',
            typeAnimated: true,
            buttons:
            {
                tryAgain:
                {
                    text: 'Try again',
                    btnClass: 'btn-red',
                    action: function () {
                        $("#pw").val("");
                        $("#confirmPW").val("");
                    }
                }
            }
        });
    </script>

}
else if (ViewBag.invalid == "invalid question")
{
<script>
    $.confirm({
        columnClass: 'col-6 text-left',
        title: 'Invalid Question',
        content: 'Security Question Assiciated With Email Provided Is Invalid',
        type: 'red',
        typeAnimated: true,
        buttons:
        {
            tryAgain:
            {
                text: 'Try again',
                btnClass: 'btn-red',
                action: function () {
                    $("#pw").val("");
                    $("#confirmPW").val("");
                }
            }
        }
    });
</script>

}
else if (ViewBag.invalid == "invalid answer")
{
<script>
    $.confirm({
        columnClass: 'col-6 text-left',
        title: 'Invalid Answer',
        content: 'The Answer Provided Is Invalid',
        type: 'red',
        typeAnimated: true,
        buttons:
        {
            tryAgain:
            {
                text: 'Try again',
                btnClass: 'btn-red',
                action: function () {
                    $("#pw").val("");
                    $("#confirmPW").val("");
                }
            }
        }
    });
</script>

}

Group_Project/Views/Login/Index.cshtml
@model Group_Project.EF.UserMaster
@{
    ViewBag.Title = "Login";
    Layout = null;
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<link rel="stylesheet" href="~/Style/Style.css" />

@using (Html.BeginForm("Login", "Login", FormMethod.Post))
{
    <form>
        <div class="containerDiv container col-lg-4 col-md-6 col-sm-8">
            <div class="col">
                <h2 class="h2">Welcome to Eco-Impact!</h2>
            </div>
            <div class="imgcontainer">
                <img src="~/Icons/logo.png" alt="Logo" class="avatar" style="width: 20%;">
            </div>
            <div class="col text-left pl-5">
                <input type="text" placeholder="username" id="loginUser" name="username" class="ml-5 w-75" required>
            </div>
            <div class="col text-left pl-5">
                <input type="password" placeholder="password" name="password" id="pwInput" class="w-75 ml-5" required>
                <div class="pl-2" style="display: inline-block; position: absolute;">
                    <i id="eyeIcon" class="display-1 fa fa-eye-slash text-secondary mt-3"></i>
                </div>
            </div>
            <div class="col">
                <i onclick="window.location='@Url.Action("ForgotPassword", "Login")'">Forgot password?</i>
            </div>
            <div class="col text-left pl-5">
                <input type="submit" id="loginBtn" value="Login" class="ml-5 w-75" />
            </div>
            <div class="col text-left pl-5">
                <input type="button" value="Create Account" class="ml-5 w-75" onclick="window.location='@Url.Action("Index", "Account")'" />
            </div>
        </div>
    </form>
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="~/Scripts/LoginScript.js"></script>

@if (ViewBag.invalid == "username")
{
    <script>
        $.confirm({
            columnClass: 'col-6 text-left',
            title: 'Invalid Username',
            content: 'The Username You Entered Could Not Be Found, Please Try Again',
            type: 'red',
            typeAnimated: true,
            buttons:
            {
                tryAgain:
                {
                    text: 'Try again',
                    btnClass: 'btn-red',
                    action: function () {
                        $("#loginUser").val("");
                        $("#pwInput").val("");
                    }
                }
            }
        });
    </script>
}
else if (ViewBag.invalid == "password")
{
    <script>
        $.confirm({
            columnClass: 'col-6 text-left',
            title: 'Invalid Username or Password',
            content: 'The Username Or Password You Entered Is Incorrect, Please Try Again',
            type: 'red',
            typeAnimated: true,
            buttons:
            {
                tryAgain:
                {
                    text: 'Try again',
                    btnClass: 'btn-red',
                    action: function () {
                        $("#loginUser").val("");
                        $("#pwInput").val("");
                    }
                }
            }
        });
    </script>
}

Group_Project/Views/Login/ResetPassword.cshtml
@{
    ViewBag.Title = "ForgotPassword";
    Layout = null;
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="~/Style/Style.css" />
<link rel="stylesheet" href="~/Style/DouglasStyles.css" />
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


@using (Html.BeginForm("UpdatePassword", "Login", FormMethod.Post))
{
    <div class="containerDiv container col-lg-5 col-md-7 col-sm-8">
        <div class="row " style="text-align: left;">
            <img src="~/Images/logo.png" width="130" style="float: left;margin-right: 40px;">
            <h3 style="font-weight: bold;margin-top: 50px;">Reset your Password</h3>
            <br>
            <br>
            <br>
            <form style="border: none;">
                <div class="form-group" style="width: 60%;margin-left: 20%;">
                    <label for="otpEnter">Enter OTP</label><br />
                    <input type="number" value="0" min="0" name="userOTP" class="form-control" id="otpEnter">
                    <small class="form-text text-muted">* One Time Password was sent to your email address</small>
                </div>
                <div class="form-group mt-3" style="width: 60%;margin-left: 20%;">
                    <label for="newPass">New Password</label><br />
                    <input type="password" name="userPassword" class="form-control" id="newPass"><i id="eyeIcon" class="display-1 fa fa-eye-slash mt-2 ml-3 text-secondary"></i><br /><br />
                </div>
                <div class="form-group" style="width: 60%;margin-left: 20%; margin-top: -4%;">
                    <label for="confirmNewPass">Confirm Password</label><br />
                    <input type="password" class="form-control" id="confirmNewPass">
                </div>
                <input type="submit" id="submitForm" class="btn" style="width: 30%; margin-left: 65%;color: black;" value="Reset" />
            </form>
        </div>
        <br>
    </div>
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="~/Scripts/resetPasswordScript.js"></script>

@if (ViewBag.invalid == "invalid")
{
    <script>
        $.confirm({
            columnClass: 'col-6 text-left',
            title: 'Invalid OTP',
            content: 'You Entered An Invalid OTP, Please Try Again',
            type: 'red',
            typeAnimated: true,
            buttons:
            {
                tryAgain:
                {
                    text: 'Try again',
                    btnClass: 'btn-red',
                    action: function () {
                        $("#otpEnter").val(0);
                        $("#pw").val("");
                        $("#confirmPW").val("");
                    }
                }
            }
        });
    </script>

}
else if (ViewBag.invalid == "valid")
{
    <script>
        $.confirm({
            columnClass: 'col-6 text-left',
            title: 'Password Updated',
            content: 'Your Password Has Successfully Been Updated',
            type: 'green',
            typeAnimated: true,
            buttons:
            {
                OK:
                {
                    text: 'Ok',
                    btnClass: 'btn-green',
                    action: function () {
                        window.location.href = "/Login/Index";
                    }
                }
            }
        });
    </script>

}